### ISSUE TITLE
The code is not working...

### ISSUE THREAD

**Issue by MegaManLegends2** [bcorfman/raven-checkers#17]
I am using Python 2.7.12 in Windows 8.1, and this is the error I get when I move one of the checkers pieces:
ShortDykeEvaluator::calculate_desirability
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1537, in __call__
    return self.func(*args)
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 587, in callit
    func(*args)
  File "C:\Users\Basel\Desktop\raven-checkers-master\gamemanager.py", line 210, in turn_finished
    self.controller2.start_turn()  # begin White's turn
  File "C:\Users\Basel\Desktop\raven-checkers-master\alphabetacontroller.py", line 39, in start_turn
    self._thinker.activate()
  File "C:\Users\Basel\Desktop\raven-checkers-master\goalthink.py", line 18, in activate
    self.arbitrate()
  File "C:\Users\Basel\Desktop\raven-checkers-master\goalthink.py", line 41, in arbitrate
    self.most_desirable = argmax_random_tie(self.evaluators, lambda e: e.calculate_desirability())
  File "C:\Users\Basel\Desktop\raven-checkers-master\utils.py", line 274, in argmax_random_tie
    return argmin_random_tie(seq, lambda x: -fn(x))
  File "C:\Users\Basel\Desktop\raven-checkers-master\utils.py", line 236, in argmin_random_tie
    best_score = fn(seq[0]); n = 0
  File "C:\Users\Basel\Desktop\raven-checkers-master\utils.py", line 274, in <lambda>
    return argmin_random_tie(seq, lambda x: -fn(x))
  File "C:\Users\Basel\Desktop\raven-checkers-master\goalthink.py", line 41, in <lambda>
    self.most_desirable = argmax_random_tie(self.evaluators, lambda e: e.calculate_desirability())
  File "C:\Users\Basel\Desktop\raven-checkers-master\evaluators.py", line 29, in calculate_desirability
    short_dyke_csp = formation_csp(self.thinker.board.short_dyke, self.thinker.board)
  File "C:\Users\Basel\Desktop\raven-checkers-master\evaluators.py", line 17, in formation_csp
    domains[var] = [item for item in pos_map[var] if board.squares[item] == player + MAN]
KeyError: 21

**Comment by bcorfman** [comment]
Hi, the current code on GitHub is not in a working state. It was last updated when I was exploring the idea of adding opening formations to the AI goals. 

The [0.4 release](https://github.com/bcorfman/raven-checkers/releases) is what you want for working code and source in a single bundle.

**Comment by MegaManLegends2** [comment]
Thanks bcorfman, this version worked perfectly! I appreciate your work.

-Basel
